openapi: 3.1.0
info:
  title: Cart API
  description: Cart API for kong microservices demo application
  version: 1.0.0
  contact:
    name: Shuhei Kawamura
    email: shuhei.kawamura@konghq.com
servers:
  - url: http://cart:3002
    description: Local development server
tags:
  - name: cart
    description: Endpoints related to the shopping cart
paths:
  /cart:
    get:
      operationId: get-cart-contents
      summary: Get cart contents
      description: Retrieve the current contents of the shopping cart
      tags:
        - cart
      responses:
        "200":
          description: A list of items in the cart
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/cart"
    post:
      operationId: add-item-to-cart
      summary: Add an item to the cart
      description: Add a new item to the shopping cart
      tags:
        - cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cart"
      responses:
        "201":
          description: Item added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cart"
    delete:
      operationId: clear-cart
      summary: Clear the cart
      description: Remove all items from the shopping cart
      tags:
        - cart
      responses:
        "204":
          description: Cart cleared
  /cart/{id}:
    delete:
      operationId: remove-item-from-cart
      summary: Remove an item from the cart
      description: Remove a specific item from the shopping cart
      tags:
        - cart
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Item removed
components:
  schemas:
    cart:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
        imageUrl:
          type: string
