openapi: 3.1.0
info:
  title: Catalogue API
  description: Catalogue API for kong microservices demo application
  version: 1.0.0
  contact:
    name: Shuhei Kawamura
    email: shuhei.kawamura@konghq.com
servers:
  - url: http://catalogue:3001
    description: Local development server
tags:
  - name: catalogue
    description: Endpoints related to the product catalogue
paths:
  /catalogue:
    get:
      operationId: get-all-products
      summary: Get all products
      description: Retrieve a list of all products in the catalogue
      tags:
        - catalogue
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/product"
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
        imageUrl:
          type: string
