name: Sync Konnect setting

on:
  push:
    paths:
      - konnect/*.yaml
      - .github/workflows/sync-konnect.yaml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Setup kongctl
        run: |
          # Install v0.3.3 for x86-64
          curl -sL https://github.com/Kong/kongctl/releases/download/v0.3.3/kongctl_linux_amd64.zip -o kongctl_linux_amd64.zip
          unzip kongctl_linux_amd64.zip -d /tmp
          sudo cp /tmp/kongctl /usr/local/bin/
          kongctl version
      - name: Plan Konnect settings
        run: |
          kongctl plan \
            -f konnect \
            --recursive \
            --pat ${{ secrets.KONNECT_TOKEN }}
      - name: Sync Konnect settings
        run: |
          kongctl sync \
            -f konnect \
            --recursive \
            --pat ${{ secrets.KONNECT_TOKEN }} \
            --auto-approve
